FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive

# update/upgrade + python3/pip3
RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y python3 python3-pip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# éviter l’erreur "externally managed" (ne plante pas si absent)
RUN rm -f /usr/lib/python*/EXTERNALLY-MANAGED || true

# Flask via pip3 (exigé)
RUN pip3 install --no-cache-dir flask

# app
WORKDIR /app
COPY ./api.py /app/api.py

# optionnel mais parlant
EXPOSE 5252

# lance le serveur Flask
CMD ["python3", "/app/api.py"]
